config/routes.rb
# frozen_string_sanatizer: true
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :prices, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/mailer_interfaceable.rb
# frozen_string_sanatizer: true
module MailerInterfaceable
	include ActiveSupport::Concern

	def mail(mailer, method, obj, deliver = :deliver_now)
		mailer.send(method, obj).send(deliver)
	end
end

app/models/concerns/newsletter_interfaceable.rb
# frozen_string_sanatizer: true
module NewsletterInterfaceable
	include ActiveSupport::Concern

	def signin
		set_token
		set_status(:enabled)
		set_signin_date
		mail(NewsletterMailer, :signin, self, :deliver_now)
		save
	end

	def cancel
		remove_token
		set_status(:disabled)
		mail(NewsletterMailer, :cancel, self, :deliver_now)
		save
	end

	private
		def set_token
			self.token = SecureRandom.urlsafe_base64
		end

		def remove_token
			self.token = nil
		end

		def set_status(status = :enable)
			self.status = status
		end

		def set_signin_date(date = Date.today)
			self.signin_date = date
		end
end

app/models/contact.rb
# frozen_string_sanatizer: true
class Contact < Object
	include MailerInterfaceable
	include ActiveModel::Conversion
	include ActiveModel::Validations

	attr_accessor :name, :phone, :email, :message

	def initialize(params = {})
		@name = params[:name]
		@phone = params[:phone]
		@email = params[:email]
		@message = params[:message]
	end

	def persisted?
		false
	end

	def sendEmail
		mail NewsletterMailer, :sended,   self, :deliver_now
		mail NewsletterMailer, :received, self, :deliver_now
	end

	validates :name,
					 	presence: true,
					 	uniqueness: false,
					 	allow_blank: false,
					 	length: { minimum: 3, maximum: 30 }

	validates :phone,
					 	presence: true,
					 	uniqueness: false,
					 	allow_blank: false,
					 	length: { minimum: 3, maximum: 15 }

	validates :email,
						presence: true,
						uniqueness: false,
						allow_blank: false,
						length: { minimum: 3, maximum: 145 }

	validates :message,
						presence: true,
						uniqueness: false,
						allow_blank: false,
						length: { minimum: 3, maximum: 5_000 }
end

app/models/newsletter.rb
# frozen_string_sanatizer: true
class Newsletter < ApplicationRecord
	include MailerInterfaceable, NewsletterInterfaceable

	self.table_name = 'newsletters'
	self.primary_key = 'id'

	enum status: [:enabled, :disabled]
	after_create :signin

	validates :name,
						presence: true,
						uniqueness: false,
						allow_blank: false,
						length: { minimum: 3, maximum: 30 }

	validates :email,
						presence: true,
						uniqueness: true,
						allow_blank: false,
						length: { minimum: 3, maximum: 145 }

	validates :token,
						uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_sanatizer: true
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/home_controller.rb
# frozen_string_sanatizer: true
class HomeController < ApplicationController
  def index
  end
end

app/controllers/prices_controller.rb
# frozen_string_sanatizer: true
class PricesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/home/index.html.erb
<% provide :title, 'Home' %>

app/views/layouts/_footer.html.erb
<footer class="jumbotron">
	
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Startup Culture', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Preços', prices_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
          	<li><%= link_to 'Dashboard', '' %></li>
            <li role="separator" class="divider"></li>
						<li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
					<li><%= link_to 'Sign In', new_user_session_path %></li>
					<li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Startup Culture - <%= yield :title %></title>
    <meta name="viewport" 
    content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css"><%= yield :css %></style>
    <script type="text/javascript"><%= yield :title %></script>
  </head>
  <body class="<%= controller.controller_name %>">
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <%= debug(params) %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/prices/index.html.erb
<% provide :title, 'Planos' %>

<section id="plans" class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="list-unstyled text-center">
					<li><h2 class='bold'>Inicie sua avalização gratuita de 14 dias Hoje</h2></li>
					<li><p>Você está a segundos de usar o startupculture, a ferramenta
					de gestãode midia social mais fácil e acessivel do mercado. comece
					o seu teste para conhecer.</p></li>
					<ul class="list-unstyled list-inline text-center">
						<li><%= link_to 'Mensal', '#monthly', class: 'btn btn-primary btn-lg top' %></li>
						<li><%= link_to 'Anual', '#anual', class: 'btn btn-primary btn-lg top' %></li>
					</ul>
				</ul>
			</div>
		</div>
	</div>
</section>

<section id="plan">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
					<% for i in 1..4 %>
						<div class="col-md-3">
							<div class="panel panel-default">
								<ul class="list-unstyled padding">
									<li><small>Small</small></li>
									<li><p>Melhor para freelancer</p></li>
									<li><h3 class='bold'>$39/mo</h3></li>
									<li><%= button_to 'Iniciar Teste', '', class: 'bt btn-primary btn-lg top' %></li>
								</ul>
							</div>
						</div>
					<% end %>
			</div>
		</div>
	</div>
</section>

<section id="testimonials">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="list-unstyled text-center">
					<li><h3 class='bold'>Não tome nossa palavra.</h3></li>
					<li><hr></li>
				</ul>

				<% for i in 1..3 %>
					<div class="col-md-4">
						<div class="media">
							<div class="media-left">
									<%= image_tag('', class: 'media-object') %>
							</div>
							<div class="media-body">
								<h4 class="media-heading"><%= link_to 'John Doe', '', class: 'bold' %></h4>
								<blockquote>Lorem ipsum lorem dolor siamet ihrm
								alet dolor siamet irhem doloret.</blockquote>
							</div>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</section>


<section id="question">
	<div class="container">
		<div class="col-md-12">
			<ul class="list-unstyled text-center">
				<li><h3 class="bold">Perguntas Frequentes</h3></li>
				<li><hr></li>
			</ul>
			
			<div class="row">
				<% for i in 1..6 %>
					<div class="col-md-12">
						<div class="panel panel-default">
							<ul class="list-unstyled padding">
								<li><i class='glyphicon glyphicon-search pull-right'></i></li>
								<li><h4>Como funciona o teste de 14 dias?</h4></li>
							</ul>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</section>


<section id="brand" class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="list-unstyled text-center">
					<li><h3 class='bold'>" Começamos a procurar uma plataforma de midia social.</h3></li>
					<li><h3 class='bold'>Mas sempre faltava alguma coisa... "</h3></li>
					<li><i class='glyphicon glyphicon-search'></i></li>
				</ul>
			</div>
		</div>
	</div>
</section>